// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjncavdxdpkwwsvcwswv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbmNhdmR4ZHBrd3dzdmN3c3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjYxMjYsImV4cCI6MjA2OTE0MjEyNn0.aVoaKCENdFXCrerVL0xpMI5XKGHuouGcs38isHk5WNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});